package main

// Auto-generated from LoLTheory Platinum synergies (~patch 16.16).
// 12 partenaires les plus joués parmi les paires à bon WR (min 0,8 % PR).
// Une override curated avec Synergies non vides remplace cette liste.

var synergies = map[string][]string{
	"Aatrox":       {"Kai'Sa", "Lee Sin", "Graves", "Ezreal", "Jhin", "Thresh", "Caitlyn", "Nautilus", "Lucian", "Viego", "Syndra", "Twisted Fate"},
	"Ahri":         {"Kai'Sa", "Ezreal", "Graves", "Lee Sin", "Jhin", "Thresh", "Caitlyn", "Viego", "Nautilus", "Vi", "Nami", "Jinx"},
	"Akali":        {"Kai'Sa", "Graves", "Lee Sin", "Thresh", "Ezreal", "Jhin", "Nautilus", "Viego", "Caitlyn", "Lucian", "Yone", "Jax"},
	"Akshan":       {"Kai'Sa", "Sylas", "Viktor", "Nami", "Nautilus", "Caitlyn", "Thresh", "Graves", "Ezreal", "Lee Sin", "Malphite", "Lucian"},
	"Alistar":      {"Kai'Sa", "Graves", "Lee Sin", "Viktor", "Jhin", "Viego", "Ezreal", "Ahri", "Tristana", "Kha'Zix", "Jinx", "Locke"},
	"Ambessa":      {"Kai'Sa", "Lee Sin", "Thresh", "Lucian", "Ezreal", "Graves", "Jhin", "Caitlyn", "Sylas", "Lulu", "Nautilus", "Vi"},
	"Amumu":        {"Kai'Sa", "Zed", "Nami", "Caitlyn", "Jinx", "Seraphine", "Viktor", "Ahri", "Darius", "Katarina"},
	"Anivia":       {"Kai'Sa", "Thresh", "Graves", "Lee Sin", "Jhin", "Ezreal", "Jinx", "Viego", "Jayce", "Lulu", "Caitlyn", "Nautilus"},
	"Annie":        {"Kai'Sa", "Jhin", "Ezreal", "Graves", "Thresh", "Lee Sin", "Nautilus", "Caitlyn", "Jinx", "Viego", "Aatrox", "Lulu"},
	"Aphelios":     {"Thresh", "Lulu", "Graves", "Lee Sin", "Viktor", "Nautilus", "Syndra", "Ahri", "Soraka", "Jayce", "Milio", "Jarvan IV"},
	"Ashe":         {"Seraphine", "Lee Sin", "Viego", "Thresh", "Graves", "Ahri", "Lulu", "Syndra", "Braum", "Viktor", "Zed", "Aatrox"},
	"AurelionSol":  {"Kai'Sa", "Thresh", "Graves", "Jhin", "Caitlyn", "Ezreal", "Nautilus", "Leona", "Jarvan IV"},
	"Aurora":       {"Ezreal", "Kai'Sa", "Lee Sin", "Aatrox", "Graves", "Caitlyn", "Thresh", "Viego", "Jhin", "Nautilus", "Lulu", "Nami"},
	"Azir":         {"Kai'Sa", "Ezreal", "Lee Sin", "Graves", "Jhin", "Thresh", "Lucian", "Bard", "Jinx", "Nautilus", "Viego", "Caitlyn"},
	"Bard":         {"Ezreal", "Jhin", "Caitlyn", "Lee Sin", "Kai'Sa", "Graves", "Sylas", "Viego", "Ahri", "Viktor", "Mordekaiser", "Ziggs"},
	"Belveth":      {"Kai'Sa", "Jhin", "Ezreal", "Thresh", "Nautilus", "Lucian", "Caitlyn", "Syndra", "Ahri", "Leona", "Jinx", "Nami"},
	"Blitzcrank":   {"Kai'Sa", "Lee Sin", "Graves", "Jhin", "Ezreal", "Viego", "Caitlyn", "Katarina", "Ahri", "Jinx", "Syndra", "Jarvan IV"},
	"Brand":        {"Jhin", "Kai'Sa", "Ezreal", "Lee Sin", "Graves", "Aatrox", "Caitlyn", "Jayce", "Katarina", "Viktor", "Zed", "Jinx"},
	"Braum":        {"Lucian", "Kai'Sa", "Graves", "Lee Sin", "Ezreal", "Jinx", "Ashe", "Syndra", "Yunara", "Caitlyn", "Viego", "Yone"},
	"Briar":        {"Kai'Sa", "Jhin", "Ezreal", "Ahri", "Thresh", "Viktor", "Nautilus", "Jinx", "Syndra", "Caitlyn", "Lulu", "Sylas"},
	"Caitlyn":      {"Graves", "Thresh", "Lee Sin", "Viktor", "Ahri", "Karma", "Morgana", "Bard", "Syndra", "Viego", "Zed", "Kha'Zix"},
	"Camille":      {"Kai'Sa", "Ezreal", "Graves", "Lee Sin", "Jhin", "Ziggs", "Viktor", "Zed", "Lucian", "Ahri", "Jayce", "Sylas"},
	"Cassiopeia":   {"Kai'Sa", "Ezreal", "Lulu", "Lee Sin", "Jinx", "Yone", "Caitlyn", "Graves", "Thresh", "Jhin", "Lucian", "Nautilus"},
	"Chogath":      {"Lee Sin", "Graves", "Jhin", "Kai'Sa", "Lucian", "Viego", "Nami", "Caitlyn", "Ezreal", "Thresh", "Jinx", "Ahri"},
	"Corki":        {"Nami", "Lee Sin", "Thresh", "Graves", "Syndra", "Ahri", "Viego", "Viktor", "Blitzcrank", "Jayce", "Renekton", "Vi"},
	"Darius":       {"Kai'Sa", "Jhin", "Graves", "Ezreal", "Caitlyn", "Lee Sin", "Thresh", "Nami", "Nautilus", "Ahri", "Jinx", "Lucian"},
	"Diana":        {"Kai'Sa", "Jhin", "Graves", "Ezreal", "Nautilus", "Thresh", "Caitlyn", "Lee Sin", "Lucian", "Vi", "Malphite", "Nocturne"},
	"DrMundo":      {"Kai'Sa", "Graves", "Lee Sin", "Ezreal", "Thresh", "Jhin", "Ahri", "Viego", "Caitlyn", "Lulu", "Tristana", "Pyke"},
	"Draven":       {"Thresh", "Nautilus", "Leona", "Pyke", "Ahri", "Viego", "Graves", "Viktor", "Lee Sin", "Syndra", "Blitzcrank", "Locke"},
	"Ekko":         {"Kai'Sa", "Nautilus", "Ezreal", "Zed", "Jhin", "Jinx", "Thresh", "Caitlyn", "Nami", "Viktor", "Yone", "Garen"},
	"Elise":        {"Ezreal", "Kai'Sa", "Caitlyn", "Zed", "Jhin", "Thresh", "Yone", "Viktor", "Nautilus", "Gangplank", "Leona", "Lulu"},
	"Evelynn":      {"Kai'Sa", "Caitlyn", "Ezreal", "Jhin", "Thresh", "Yasuo", "Zed", "Nautilus", "Yone", "Pantheon", "Lulu", "Viktor"},
	"Ezreal":       {"Karma", "Lee Sin", "Graves", "Viktor", "Ahri", "Bard", "Sylas", "Thresh", "Viego", "Yone", "Syndra", "Camille"},
	"Fiddlesticks": {"Kai'Sa", "Jhin", "Zed", "Thresh", "Ezreal", "Nautilus", "Caitlyn", "Tristana", "Pyke", "Darius", "Nami", "Leona"},
	"Fiora":        {"Kai'Sa", "Ezreal", "Jhin", "Lee Sin", "Nautilus", "Thresh", "Graves", "Locke", "Lulu", "Caitlyn", "Jinx", "Yunara"},
	"Fizz":         {"Kai'Sa", "Jhin", "Lee Sin", "Ezreal", "Graves", "Thresh", "Caitlyn", "Nautilus", "Viego", "Lucian", "Nami", "Jinx"},
	"Galio":        {"Kai'Sa", "Lee Sin", "Graves", "Lulu", "Ezreal", "Lucian", "Jhin", "Nautilus", "Thresh", "Caitlyn", "Viego", "Jinx"},
	"Gangplank":    {"Kai'Sa", "Ezreal", "Graves", "Jhin", "Lee Sin", "Thresh", "Nautilus", "Caitlyn", "Viktor", "Ahri", "Leona", "Yunara"},
	"Garen":        {"Kai'Sa", "Graves", "Caitlyn", "Thresh", "Jhin", "Ahri", "Ezreal", "Lee Sin", "Viego", "Lucian", "Nautilus", "Lulu"},
	"Gnar":         {"Kai'Sa", "Ezreal", "Graves", "Thresh", "Ahri", "Nautilus", "Lee Sin", "Viego", "Jhin", "Syndra", "Lulu", "Caitlyn"},
	"Gragas":       {"Kai'Sa", "Zed", "Graves", "Lee Sin", "Jhin", "Viego", "Caitlyn", "Ezreal", "Lucian", "Thresh", "Yasuo", "Lulu"},
	"Graves":       {"Kai'Sa", "Thresh", "Ezreal", "Jhin", "Caitlyn", "Nautilus", "Lucian", "Ahri", "Sylas", "Jinx", "Aatrox", "Jayce"},
	"Gwen":         {"Ezreal", "Kai'Sa", "Graves", "Lee Sin", "Jhin", "Jinx", "Zed", "Nautilus", "Thresh", "Caitlyn", "Lucian", "Yone"},
	"Hecarim":      {"Kai'Sa", "Jhin", "Ezreal", "Thresh", "Lucian", "Nami", "Nautilus", "Zed", "Pyke", "Ahri", "Jinx", "Karma"},
	"Heimerdinger": {"Kai'Sa", "Jhin", "Caitlyn", "Ezreal", "Yunara", "Lee Sin", "Jarvan IV", "Thresh", "Zed", "Yone"},
	"Hwei":         {"Kai'Sa", "Ezreal", "Jhin", "Thresh", "Lee Sin", "Viego", "Graves", "Caitlyn", "Nautilus", "Lucian", "Karma", "Kha'Zix"},
	"Illaoi":       {"Lee Sin", "Kai'Sa", "Ezreal", "Graves", "Jinx", "Lulu", "Viego", "Thresh", "Lucian", "Pyke", "Caitlyn", "Malzahar"},
	"Irelia":       {"Kai'Sa", "Jhin", "Ezreal", "Graves", "Nautilus", "Thresh", "Lee Sin", "Caitlyn", "Ahri", "Lucian", "Tristana", "Jarvan IV"},
	"Ivern":        {"Kai'Sa", "Nautilus", "Caitlyn", "Ezreal", "Yasuo", "Thresh", "Yunara", "Jhin", "Jinx", "Syndra", "Yone", "Zed"},
	"Janna":        {"Jhin", "Ezreal", "Graves", "Kai'Sa", "Jinx", "Lee Sin", "Caitlyn", "Zed", "Viego", "Malphite", "Locke", "Syndra"},
	"JarvanIV":     {"Kai'Sa", "Ezreal", "Jhin", "Thresh", "Caitlyn", "Lucian", "Viktor", "Nautilus", "Ahri", "Jinx", "Pyke", "Leona"},
	"Jax":          {"Kai'Sa", "Ezreal", "Thresh", "Lee Sin", "Graves", "Jhin", "Caitlyn", "Lucian", "Nautilus", "Sylas", "Viktor", "Ahri"},
	"Jayce":        {"Kai'Sa", "Lee Sin", "Jhin", "Graves", "Ezreal", "Thresh", "Caitlyn", "Lucian", "Nautilus", "Leona", "Viego", "Sylas"},
	"Jhin":         {"Lee Sin", "Graves", "Thresh", "Bard", "Karma", "Ahri", "Viktor", "Nautilus", "Syndra", "Viego", "Katarina", "Leona"},
	"Jinx":         {"Lulu", "Thresh", "Graves", "Milio", "Viktor", "Viego", "Lee Sin", "Ahri", "Karma", "Nautilus", "Jarvan IV", "Kha'Zix"},
	"KSante":       {"Kai'Sa", "Jhin", "Ezreal", "Graves", "Lee Sin", "Thresh", "Syndra", "Nautilus", "Lucian", "Viego", "Leona", "Camille"},
	"Kaisa":        {"Nautilus", "Thresh", "Lee Sin", "Graves", "Leona", "Pyke", "Syndra", "Blitzcrank", "Viktor", "Yone", "Viego", "Ahri"},
	"Kalista":      {"Thresh", "Graves", "Leona", "Nautilus", "Lee Sin", "Alistar", "Jayce", "Pyke", "Viktor", "Ahri", "Akali", "Sylas"},
	"Karma":        {"Ezreal", "Jhin", "Caitlyn", "Lee Sin", "Graves", "Kai'Sa", "Ahri", "Jinx", "Viego", "Renekton", "Yunara", "Zed"},
	"Karthus":      {"Kai'Sa", "Ezreal", "Caitlyn", "Nami", "Zed", "Yone", "Jhin", "Thresh", "Lucian", "Nautilus", "Tristana", "Milio"},
	"Kassadin":     {"Kai'Sa", "Ezreal", "Graves", "Caitlyn", "Viego", "Lulu", "Jhin", "Lee Sin", "Thresh", "Lucian", "Nautilus", "Leona"},
	"Katarina":     {"Kai'Sa", "Ezreal", "Jhin", "Graves", "Thresh", "Lee Sin", "Caitlyn", "Lucian", "Viego", "Lulu", "Nautilus", "Jinx"},
	"Kayle":        {"Kai'Sa", "Jhin", "Lucian", "Lulu", "Graves", "Yasuo", "Thresh", "Zed", "Nautilus", "Viego", "Caitlyn", "Nami"},
	"Kayn":         {"Kai'Sa", "Thresh", "Ezreal", "Jhin", "Nautilus", "Ahri", "Lulu", "Jinx", "Caitlyn", "Lucian", "Sylas", "Syndra"},
	"Kennen":       {"Kai'Sa", "Ezreal", "Zed", "Thresh", "Lucian", "Graves", "Aphelios", "Jinx", "Viego", "Viktor", "Yasuo", "Lee Sin"},
	"Khazix":       {"Kai'Sa", "Ezreal", "Thresh", "Jhin", "Caitlyn", "Lucian", "Jinx", "Nautilus", "Lulu", "Pyke", "Zed", "Ahri"},
	"Kindred":      {"Ezreal", "Kai'Sa", "Nautilus", "Thresh", "Ahri", "Jhin", "Viktor", "Caitlyn", "K'Sante", "Jayce", "Jinx", "Sylas"},
	"Kled":         {"Kai'Sa", "Ezreal", "Jhin", "Caitlyn", "Lee Sin", "Viktor", "Yunara", "Locke", "Viego", "Jinx", "Ahri", "Graves"},
	"KogMaw":       {"Lulu", "Graves", "Lee Sin", "Viktor", "Milio", "Zed", "Ahri", "Nami", "Jax", "Kha'Zix", "Viego", "Wukong"},
	"Leblanc":      {"Kai'Sa", "Graves", "Lee Sin", "Ezreal", "Jhin", "Thresh", "Lucian", "Caitlyn", "Yone", "Karma", "Nautilus", "Jinx"},
	"LeeSin":       {"Kai'Sa", "Ezreal", "Thresh", "Jhin", "Lucian", "Nautilus", "Caitlyn", "Syndra", "Ahri", "Viktor", "Jayce", "Aatrox"},
	"Leona":        {"Kai'Sa", "Lee Sin", "Graves", "Jhin", "Ezreal", "Caitlyn", "Viego", "Ahri", "Samira", "Tristana", "Jarvan IV", "Locke"},
	"Lillia":       {"Jhin", "Kai'Sa", "Lucian", "Zed", "Ezreal", "Caitlyn", "Nautilus", "Thresh", "Yasuo", "Jayce", "Lulu", "Pyke"},
	"Lissandra":    {"Kai'Sa", "Graves", "Jhin", "Lee Sin", "Ezreal", "Thresh", "Caitlyn", "Lucian", "Viego", "Jinx", "Seraphine", "Pyke"},
	"Locke":        {"Kai'Sa", "Jhin", "Caitlyn", "Ezreal", "Lee Sin", "Graves", "Viego", "Nautilus", "Thresh", "Leona", "Lucian", "Nami"},
	"Lucian":       {"Milio", "Nami", "Lee Sin", "Graves", "Braum", "Yuumi", "Viktor", "Thresh", "Syndra", "Ahri", "Viego", "Kha'Zix"},
	"Lulu":         {"Yunara", "Jinx", "Kai'Sa", "Twitch", "Lee Sin", "Graves", "Zeri", "Kog'Maw", "Aphelios", "Viego", "Tristana", "Ahri"},
	"Lux":          {"Caitlyn", "Jhin", "Ezreal", "Graves", "Lee Sin", "Zed", "Kai'Sa", "Viego", "Aatrox", "Jarvan IV", "Viktor", "Kha'Zix"},
	"Malphite":     {"Kai'Sa", "Ezreal", "Thresh", "Lee Sin", "Caitlyn", "Jhin", "Yasuo", "Graves", "Nami", "Nautilus", "Ahri", "Lucian"},
	"Malzahar":     {"Kai'Sa", "Graves", "Thresh", "Ezreal", "Caitlyn", "Viego", "Nautilus", "Jhin", "Lucian", "Lee Sin", "Bard", "Kha'Zix"},
	"Maokai":       {"Kai'Sa", "Ezreal", "Jhin", "Graves", "Viktor", "Wukong", "Lee Sin", "Jinx", "Viego", "Caitlyn", "Jarvan IV", "Zed"},
	"MasterYi":     {"Kai'Sa", "Ezreal", "Thresh", "Jhin", "Caitlyn", "Jinx", "Lulu", "Nautilus", "Lucian", "Malphite", "Sylas", "Tristana"},
	"Mel":          {"Graves", "Lee Sin", "Nautilus", "Camille", "Thresh", "Zed", "Pyke", "Senna", "Viktor", "Yasuo", "Viego", "Aatrox"},
	"Milio":        {"Lucian", "Jinx", "Caitlyn", "Graves", "Lee Sin", "Kai'Sa", "Ahri", "Yunara", "Kha'Zix", "Zed", "Jax", "Viktor"},
	"MissFortune":  {"Thresh", "Graves", "Nautilus", "Leona", "Rell", "Viego", "Syndra", "Lee Sin", "Viktor", "Darius", "Jarvan IV", "Seraphine"},
	"MonkeyKing":   {"Kai'Sa", "Jhin", "Ezreal", "Caitlyn", "Nautilus", "Thresh", "Jayce", "Syndra", "Katarina", "Lulu", "Jinx", "Leona"},
	"Mordekaiser":  {"Kai'Sa", "Jhin", "Zed", "Ezreal", "Graves", "Lee Sin", "Thresh", "Lulu", "Jinx", "Yasuo", "Bard", "Caitlyn"},
	"Morgana":      {"Caitlyn", "Kai'Sa", "Jhin", "Ezreal", "Graves", "Lee Sin", "Zed", "Viego", "Ahri", "Katarina", "Aatrox", "Jarvan IV"},
	"Naafiri":      {"Kai'Sa", "Ezreal", "Jhin", "Caitlyn", "Thresh", "Viktor", "Nautilus", "Bard", "Sylas", "Karma", "Lucian", "Akali"},
	"Nami":         {"Lucian", "Kai'Sa", "Graves", "Viego", "Ahri", "Caitlyn", "Jhin", "Ezreal", "Lee Sin", "Darius", "Malphite", "Zed"},
	"Nasus":        {"Kai'Sa", "Caitlyn", "Graves", "Lee Sin", "Viego", "Thresh", "Jhin", "Ezreal", "Ahri", "Jinx", "Lucian", "Viktor"},
	"Nautilus":     {"Kai'Sa", "Graves", "Lee Sin", "Samira", "Jhin", "Viego", "Ezreal", "Ahri", "Aatrox", "Tristana", "Caitlyn", "Twisted Fate"},
	"Neeko":        {"Kai'Sa", "Ezreal", "Caitlyn", "Jhin", "Lee Sin", "Graves", "Viktor", "Yasuo", "Jarvan IV", "Sylas"},
	"Nidalee":      {"Kai'Sa", "Jhin", "Thresh", "Zed", "Nautilus", "Ezreal", "Leona", "Caitlyn", "Renekton", "Lucian", "Yasuo", "Jayce"},
	"Nilah":        {"Graves", "Pyke", "Lee Sin", "Garen", "Zed", "Thresh", "Camille", "Gnar", "Jarvan IV", "Nami", "Yone", "Seraphine"},
	"Nocturne":     {"Kai'Sa", "Caitlyn", "Jhin", "Ezreal", "Thresh", "Jinx", "Leona", "Lucian", "Karma", "Lulu", "Sylas", "Yunara"},
	"Nunu":         {"Kai'Sa", "Jhin", "Ezreal", "Caitlyn", "Yone", "Thresh", "Nautilus", "Syndra", "Leona", "Lulu", "Blitzcrank", "Jayce"},
	"Olaf":         {"Kai'Sa", "Lee Sin", "Ezreal", "Thresh", "Jhin", "Nautilus", "Graves", "Caitlyn", "Syndra", "Nami", "Viego", "Ahri"},
	"Orianna":      {"Kai'Sa", "Thresh", "Jhin", "Lee Sin", "Graves", "Nocturne", "Ezreal", "Caitlyn", "Jarvan IV", "Nautilus", "Jinx", "Lucian"},
	"Ornn":         {"Kai'Sa", "Thresh", "Graves", "Viktor", "Caitlyn", "Jhin", "Lee Sin", "Jinx", "Ezreal", "Nami", "Nautilus", "Viego"},
	"Pantheon":     {"Kai'Sa", "Lee Sin", "Jhin", "Ezreal", "Graves", "Viego", "Lucian", "Viktor", "Aatrox", "Sylas", "Zed", "Ahri"},
	"Poppy":        {"Kai'Sa", "Graves", "Ezreal", "Jhin", "Lee Sin", "Viktor", "Zed", "Syndra", "Caitlyn", "Yunara", "Garen", "Jayce"},
	"Pyke":         {"Kai'Sa", "Lee Sin", "Graves", "Ezreal", "Ahri", "Jhin", "Caitlyn", "Jarvan IV", "Lucian", "Jayce", "Tristana", "Kha'Zix"},
	"Qiyana":       {"Kai'Sa", "Thresh", "Nautilus", "Jhin", "Jinx", "Lulu", "Caitlyn", "Ezreal", "Lucian", "Nami", "Sylas", "Leona"},
	"Quinn":        {"Kai'Sa", "Thresh", "Caitlyn", "Jhin", "Tristana"},
	"Rakan":        {"Xayah", "Kai'Sa", "Lee Sin", "Graves", "Ahri", "Ezreal", "Yone", "Sylas", "Jhin", "Syndra", "Yasuo", "Wukong"},
	"Rammus":       {"Caitlyn", "Kai'Sa", "Ahri", "Syndra", "Ezreal", "Garen"},
	"RekSai":       {"Kai'Sa", "Ezreal", "Nautilus", "Caitlyn", "Viktor", "Lissandra", "Lulu", "Jhin", "Jayce", "Thresh", "Ashe", "Katarina"},
	"Rell":         {"Kai'Sa", "Lee Sin", "Graves", "Miss Fortune", "Viego", "Jhin", "Ezreal", "Jinx", "Caitlyn", "Sylas", "Jarvan IV", "Katarina"},
	"Renata":       {"Lucian", "Jinx", "Caitlyn", "Graves", "Lee Sin", "Kai'Sa", "Ahri", "Yunara", "Kha'Zix", "Zed", "Jax", "Viktor"},
	"Renekton":     {"Kai'Sa", "Lee Sin", "Jhin", "Ezreal", "Graves", "Nautilus", "Syndra", "Thresh", "Caitlyn", "Ahri", "Karma", "Lucian"},
	"Rengar":       {"Kai'Sa", "Ezreal", "Jhin", "Nami", "Thresh", "Caitlyn", "Karma", "Ahri", "Lucian", "Nautilus", "Sylas", "Leona"},
	"Riven":        {"Kai'Sa", "Graves", "Ezreal", "Jhin", "Thresh", "Viego", "Jinx", "Caitlyn", "Lee Sin", "Lulu", "Nautilus", "Leona"},
	"Rumble":       {"Kai'Sa", "Ezreal", "Graves", "Jhin", "Jarvan IV", "Lee Sin", "Zed", "Wukong", "Thresh", "Twisted Fate", "Nautilus", "Jinx"},
	"Ryze":         {"Lee Sin", "Kai'Sa", "Ezreal", "Jhin", "Graves", "Nautilus", "Lucian", "Thresh", "Caitlyn", "Karma", "Ambessa", "Aatrox"},
	"Samira":       {"Nautilus", "Leona", "Thresh", "Graves", "Lee Sin", "Pyke", "Rell", "Ahri", "Blitzcrank", "Sylas", "Viego", "Jarvan IV"},
	"Sejuani":      {"Kai'Sa", "Thresh", "Jinx", "Yone", "Nautilus", "Pyke", "Viktor", "Caitlyn", "Camille", "Lucian", "Darius", "Ezreal"},
	"Senna":        {"Ezreal", "Caitlyn", "Kai'Sa", "Jhin", "Graves", "Lee Sin", "Viego", "Viktor", "Ahri", "Locke", "Zed", "Kha'Zix"},
	"Seraphine":    {"Ashe", "Ezreal", "Graves", "Kai'Sa", "Lee Sin", "Viego", "Jhin", "Caitlyn", "Zed", "Aatrox", "Ahri", "Kha'Zix"},
	"Sett":         {"Kai'Sa", "Graves", "Thresh", "Jhin", "Ezreal", "Caitlyn", "Lee Sin", "Lulu", "Jinx", "Ahri", "Lucian", "Nautilus"},
	"Shaco":        {"Kai'Sa", "Caitlyn", "Jhin", "Ezreal", "Thresh", "Nautilus", "Leona", "Jinx", "Zed", "Lulu", "Ahri", "Nami"},
	"Shen":         {"Kai'Sa", "Caitlyn", "Ezreal", "Graves", "Thresh", "Nautilus", "Lucian", "Lee Sin", "Syndra", "Jinx", "Jhin", "Nami"},
	"Shyvana":      {"Ezreal", "Kai'Sa", "Jhin", "Lulu", "Thresh", "Caitlyn", "Ahri", "Jinx", "Lucian", "Nautilus", "Syndra", "Karma"},
	"Singed":       {"Kai'Sa", "Graves", "Jhin", "Ezreal", "Lee Sin", "Thresh", "Nautilus", "Viego", "Syndra", "Caitlyn", "Leona", "Pyke"},
	"Sion":         {"Kai'Sa", "Graves", "Jhin", "Ahri", "Caitlyn", "Ezreal", "Lee Sin", "Viego", "Thresh", "Lulu", "Karma", "Jinx"},
	"Sivir":        {"Lee Sin", "Graves", "Yuumi", "Viktor", "Lulu", "Thresh", "Syndra", "Bard", "Katarina", "Sylas", "Ahri", "Alistar"},
	"Skarner":      {"Kai'Sa", "Ezreal", "Jhin", "Caitlyn", "Thresh", "Viktor", "Nautilus", "Bard", "Sylas", "Karma", "Lucian", "Akali"},
	"Smolder":      {"Lee Sin", "Thresh", "Viktor", "Nami", "Graves", "Syndra", "Mordekaiser", "Katarina", "Locke", "Karma", "Ahri", "Bard"},
	"Sona":         {"Ezreal", "Kai'Sa", "Graves", "Jhin", "Viego", "Lucian", "Jinx", "Lee Sin", "Malzahar", "Yunara", "Zed", "Ahri"},
	"Soraka":       {"Kai'Sa", "Ezreal", "Caitlyn", "Graves", "Lee Sin", "Ahri", "Jinx", "Aphelios", "Jhin", "Syndra", "Kha'Zix", "Viego"},
	"Swain":        {"Kai'Sa", "Jhin", "Graves", "Lee Sin", "Ezreal", "Lucian", "Caitlyn", "Viego", "Aatrox", "Yone", "Jayce", "Jinx"},
	"Sylas":        {"Kai'Sa", "Graves", "Ezreal", "Lee Sin", "Jhin", "Thresh", "Caitlyn", "Nautilus", "Lucian", "Yone", "Lulu", "Viego"},
	"Syndra":       {"Kai'Sa", "Lee Sin", "Graves", "Jhin", "Ezreal", "Thresh", "Nautilus", "Caitlyn", "Viego", "Lucian", "Nami", "Renekton"},
	"TahmKench":    {"Kai'Sa", "Graves", "Jhin", "Lee Sin", "Jinx", "Viktor", "Viego", "Aatrox", "Caitlyn", "Ezreal", "Ahri", "Jax"},
	"Taliyah":      {"Kai'Sa", "Jhin", "Lee Sin", "Nautilus", "Caitlyn", "Ezreal", "Jarvan IV", "Graves", "Jinx", "Thresh", "Pyke", "Ambessa"},
	"Talon":        {"Kai'Sa", "Thresh", "Caitlyn", "Jhin", "Ahri", "Ezreal", "Lulu", "Nautilus", "Sylas", "Katarina", "Lucian", "Yunara"},
	"Taric":        {"Kai'Sa", "Graves", "Jhin", "Viego", "Jayce", "Viktor", "Ahri", "Sylas", "Hecarim", "Tristana", "Yunara", "Zed"},
	"Teemo":        {"Kai'Sa", "Thresh", "Graves", "Caitlyn", "Lee Sin", "Ezreal", "Zed", "Viego", "Lucian", "Jinx", "Nautilus", "Jhin"},
	"Thresh":       {"Kai'Sa", "Lee Sin", "Graves", "Aphelios", "Jinx", "Caitlyn", "Jhin", "Viego", "Ezreal", "Ahri", "Viktor", "Jayce"},
	"Tristana":     {"Thresh", "Lulu", "Graves", "Nautilus", "Lee Sin", "Viktor", "Leona", "Ahri", "Nami", "Pyke", "Viego", "Syndra"},
	"Trundle":      {"Kai'Sa", "Lee Sin", "Graves", "Ezreal", "Nautilus", "Jhin", "Thresh", "Caitlyn", "Kha'Zix", "Karma", "Viego", "Nami"},
	"Tryndamere":   {"Kai'Sa", "Jhin", "Thresh", "Lee Sin", "Ezreal", "Caitlyn", "Graves", "Viktor", "Nami", "Lulu", "Viego", "Lux"},
	"TwistedFate":  {"Kai'Sa", "Lee Sin", "Graves", "Ezreal", "Jhin", "Thresh", "Nautilus", "Yone", "Lulu", "Aatrox", "Jinx", "Lucian"},
	"Twitch":       {"Lulu", "Yuumi", "Graves", "Ahri", "Viktor", "Thresh", "Viego", "Karma", "Locke", "Lee Sin", "Nami", "Syndra"},
	"Udyr":         {"Kai'Sa", "Ezreal", "Thresh", "Caitlyn", "Ahri", "Syndra", "Jinx", "Nami", "Jax", "Malphite", "Jhin", "Pyke"},
	"Urgot":        {"Kai'Sa", "Graves", "Jhin", "Ezreal", "Nami", "Thresh", "Lee Sin", "Ahri", "Caitlyn", "Lucian", "Viego", "Viktor"},
	"Varus":        {"Graves", "Thresh", "Viego", "Lulu", "Zed", "Syndra", "Viktor", "Aatrox", "Lee Sin", "Leona", "Dr. Mundo", "Malphite"},
	"Vayne":        {"Lulu", "Graves", "Thresh", "Lee Sin", "Ahri", "Syndra", "Viktor", "Locke", "Viego", "Nami", "Leona", "Pyke"},
	"Veigar":       {"Kai'Sa", "Graves", "Caitlyn", "Lee Sin", "Nami", "Thresh", "Jhin", "Ezreal", "Lucian", "Jinx", "Viego", "Lulu"},
	"Velkoz":       {"Jhin", "Ezreal", "Kai'Sa", "Lee Sin", "Zed", "Graves", "Katarina", "Caitlyn", "Viego", "Ahri", "Jarvan IV", "Vi"},
	"Vex":          {"Kai'Sa", "Thresh", "Jhin", "Lee Sin", "Graves", "Nautilus", "Blitzcrank", "Ezreal", "Jinx", "Viego", "Lucian", "Caitlyn"},
	"Vi":           {"Kai'Sa", "Ahri", "Ezreal", "Caitlyn", "Thresh", "Lucian", "Jhin", "Lulu", "Yone", "Jinx", "Nautilus", "Viktor"},
	"Viego":        {"Kai'Sa", "Thresh", "Ezreal", "Nautilus", "Jhin", "Caitlyn", "Ahri", "Jinx", "Lulu", "Nami", "Syndra", "Lucian"},
	"Viktor":       {"Kai'Sa", "Ezreal", "Graves", "Lee Sin", "Jhin", "Caitlyn", "Thresh", "Nautilus", "Lucian", "Jinx", "Viego", "Lulu"},
	"Vladimir":     {"Kai'Sa", "Lee Sin", "Thresh", "Jhin", "Ezreal", "Graves", "Caitlyn", "Leona", "Nautilus", "Tristana", "Jarvan IV", "Viego"},
	"Volibear":     {"Kai'Sa", "Lee Sin", "Ezreal", "Thresh", "Jhin", "Caitlyn", "Yasuo", "Syndra", "Nautilus", "Lucian", "Nami", "Graves"},
	"Warwick":      {"Kai'Sa", "Ezreal", "Caitlyn", "Nautilus", "Thresh", "Viktor", "Camille", "Jinx", "Milio", "Lulu", "Yasuo", "Pyke"},
	"Xayah":        {"Rakan", "Lee Sin", "Thresh", "Viktor", "Nautilus", "Graves", "Leona", "Viego", "Ahri", "Jayce", "Nocturne", "Sylas"},
	"Xerath":       {"Kai'Sa", "Graves", "Ezreal", "Caitlyn", "Thresh", "Jhin", "Lee Sin", "Viego", "Nautilus", "Lucian", "Lulu", "Jinx"},
	"XinZhao":      {"Kai'Sa", "Sylas", "Ezreal", "Jhin", "Caitlyn", "Lucian", "Nautilus", "Jayce", "Syndra", "Karma", "Thresh", "Viktor"},
	"Yasuo":        {"Kai'Sa", "Jhin", "Lee Sin", "Nautilus", "Thresh", "Ezreal", "Malphite", "Diana", "Caitlyn", "Graves", "Pyke", "Lulu"},
	"Yone":         {"Kai'Sa", "Ezreal", "Lee Sin", "Thresh", "Graves", "Jhin", "Lucian", "Nautilus", "Caitlyn", "Viego", "Twisted Fate", "Ahri"},
	"Yorick":       {"Kai'Sa", "Jhin", "Lee Sin", "Caitlyn", "Thresh", "Ezreal", "Nautilus", "Jinx", "Ahri", "Viego", "Graves", "Lucian"},
	"Yunara":       {"Lulu", "Lee Sin", "Graves", "Thresh", "Viktor", "Ahri", "Viego", "Syndra", "Nautilus", "Karma", "Jayce", "Sylas"},
	"Yuumi":        {"Zeri", "Lucian", "Lee Sin", "Ezreal", "Tristana", "Graves", "Kai'Sa", "Sivir", "Twitch", "Viktor", "Ahri", "Malphite"},
	"Zaahen":       {"Kai'Sa", "Lee Sin", "Graves", "Ezreal", "Nautilus", "Jhin", "Thresh", "Caitlyn", "Kha'Zix", "Karma", "Viego", "Nami"},
	"Zac":          {"Kai'Sa", "Thresh", "Jhin", "Ezreal", "Leona", "Lucian", "Caitlyn", "Jinx", "Ahri", "Pyke", "Milio", "Zed"},
	"Zed":          {"Kai'Sa", "Ezreal", "Thresh", "Lee Sin", "Jhin", "Caitlyn", "Nautilus", "Graves", "Mordekaiser", "Viego", "Viktor", "Leona"},
	"Zeri":         {"Yuumi", "Lulu", "Graves", "Viktor", "Lee Sin", "Katarina", "Talon", "Viego", "Ahri", "Jax", "Nautilus", "Syndra"},
	"Ziggs":        {"Graves", "Zed", "Camille", "Lee Sin", "Leona", "Bard", "Thresh", "Yone", "Kha'Zix", "Viego", "Aatrox", "Pyke"},
	"Zilean":       {"Kai'Sa", "Jhin", "Ezreal", "Graves", "Jinx", "Nocturne", "Ahri", "Vi", "Viego", "Caitlyn", "Hecarim", "Lee Sin"},
	"Zoe":          {"Kai'Sa", "Ezreal", "Lee Sin", "Caitlyn", "Graves", "Thresh", "Jinx", "Lucian", "Leona", "Jayce", "Lulu", "Vi"},
	"Zyra":         {"Jhin", "Caitlyn", "Kai'Sa", "Ezreal", "Graves", "Lee Sin", "Jayce", "Syndra", "Viego", "Viktor", "Darius", "Hwei"},
}
