const $=id=>document.getElementById(id);let roster=[],visible=new Set(),focusKey=null,timer,version='',lastPhase='';
const demo=[34,53,25,238];const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const iconUrl=c=>`https://ddragon.leagueoflegends.com/cdn/${version}/img/champion/${encodeURIComponent(c.icon)}`;
function card(c,i){const spells=c.important.map(s=>`<div class="spell"><span class="spell-key">${esc(s.spell)}</span><div><div class="spell-name">${esc(s.name)}</div>${s.note?`<div class="spell-note">${esc(s.note)}</div>`:''}</div><span class="spell-cd">${esc(s.cd||'—')}</span></div>`).join('');return `<article class="card ${c.key===focusKey?'focus':''}" data-key="${c.key}"><div class="card-head"><img class="portrait" src="${iconUrl(c)}"><div><h4>${i+1}. ${esc(c.name)}</h4><div class="title">${esc(c.title)}</div></div><span class="source">${c.source==='curated'?'curated':'auto'}</span></div><div class="spells">${spells}</div><div class="summary"><span>À retenir</span><strong>${esc(c.summary)}</strong></div>${c.window?`<div class="window">${esc(c.window)}</div>`:''}</article>`}
function visibleCards(){return roster.filter(c=>visible.has(c.key))}
function renderNav(){const nav=$('champ-nav');nav.classList.toggle('hidden',!roster.length);nav.innerHTML=roster.map(c=>`<button type="button" class="champ-toggle ${visible.has(c.key)?'on':''}" data-key="${c.key}" title="${esc(c.name)}" aria-pressed="${visible.has(c.key)}"><img src="${iconUrl(c)}" alt="${esc(c.name)}"><span class="tick">✓</span></button>`).join('');nav.querySelectorAll('.champ-toggle').forEach(btn=>btn.onclick=()=>{const key=+btn.dataset.key;if(visible.has(key)){visible.delete(key);if(focusKey===key)focusKey=null}else visible.add(key);render()})}
function render(){const cards=visibleCards();$('enemy-count').textContent=`${cards.length}/${roster.length||5}`;$('empty').classList.toggle('hidden',roster.length>0);renderNav();$('cards').innerHTML=cards.map(card).join('');document.querySelectorAll('.card').forEach(x=>x.onclick=()=>{focusKey=+x.dataset.key;render()})}
function setRoster(cards,reset){const prev=new Set(roster.map(c=>c.key));const next=new Set();for(const c of cards){if(reset||!prev.has(c.key)||visible.has(c.key))next.add(c.key)}roster=cards;visible=next;if(focusKey!=null&&!visible.has(focusKey))focusKey=null;render()}
async function cards(ids,reset){if(!ids.length){setRoster([]);return}const r=await fetch('/api/cards?ids='+ids.join(','));setRoster(await r.json(),reset)}
async function status(){try{const s=await (await fetch('/api/status')).json();version=s.version||version;$('patch').textContent=version;$('dot').classList.toggle('on',!!s.connected);$('status').textContent=s.connected?'League connecté':'League non détecté';$('phase').textContent=s.phase||'—';if(s.phase==='ChampSelect'){if(lastPhase!=='ChampSelect')window.__manual=false;$('hero-title').textContent='Champion select détectée';$('hero-copy').textContent=s.enemies?.length?'Les picks ennemis visibles sont chargés automatiquement.':'En attente des picks ennemis visibles…';if(!window.__manual)await cards(s.enemies||[])}else if(s.connected){$('hero-title').textContent=`Client détecté · ${s.phase}`;$('hero-copy').textContent='CD Scout chargera automatiquement les ennemis au prochain champion select.'}lastPhase=s.phase||lastPhase}catch(e){$('status').textContent='Erreur locale'}}
$('quit').onclick=async()=>{try{await fetch('/api/quit',{method:'POST'})}catch(_){};document.body.innerHTML='<div style="padding:40px;font-family:system-ui;color:#ddd;background:#080d18;min-height:100vh"><h2>CD Scout fermé.</h2><p>Tu peux fermer cet onglet.</p></div>'};
$('demo').onclick=async()=>{window.__manual=true;focusKey=null;$('hero-title').textContent='Mode démo';$('hero-copy').textContent='Exemple de lecture rapide avec quelques champions.';await cards(demo,true)};
$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const q=$('search').value.trim();if(!q){$('results').classList.add('hidden');return}const rs=await (await fetch('/api/search?q='+encodeURIComponent(q))).json();$('results').innerHTML=rs.map(r=>`<div class="result" data-key="${r.key}"><span>${esc(r.name)}</span><small>${esc(r.title)}</small></div>`).join('');$('results').classList.toggle('hidden',!rs.length);document.querySelectorAll('.result').forEach(row=>row.onclick=async()=>{window.__manual=true;$('search').value='';$('results').classList.add('hidden');const c=await (await fetch('/api/card?key='+row.dataset.key)).json();focusKey=c.key;setRoster([c],true);$('hero-title').textContent=c.name;$('hero-copy').textContent='Recherche manuelle.'})},180)};
document.onclick=e=>{if(!e.target.closest('.search-wrap'))$('results').classList.add('hidden')};document.onkeydown=e=>{if(document.activeElement===$('search'))return;const list=visibleCards();const n=+e.key;if(n>=1&&n<=list.length){focusKey=list[n-1].key;render()}};status();setInterval(status,1500);
