name: release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Build
        run: go build -ldflags="-s -w -H=windowsgui -X main.appVersion=${{ github.ref_name }}" -o lol-cd-scout-native.exe .
      - uses: softprops/action-gh-release@v2
        with:
          files: lol-cd-scout-native.exe
